package org.sakaiproject.provider.user;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import org.w3c.dom.Element;
import com.sun.xml.ws.api.message.Headers;
import com.sun.xml.ws.developer.WSBindingProvider;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * GetConstInfo service = new GetConstInfo();
 * GetConstInfoSoap portType = service.getGetConstInfoSoap();
 * portType.getConstituent(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "GetConstInfo", targetNamespace = "http://ico.edu/", wsdlLocation = "https://my.ico.edu/custom/ico/GetConstInfo.asmx?wsdl")
public class GetConstInfo extends Service {

	private final static URL GETCONSTINFO_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.sakaiproject.provider.user.GetConstInfo.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.sakaiproject.provider.user.GetConstInfo.class.getResource(".");
			url = new URL(
					baseUrl,
					"https://my.ico.edu/custom/ico/GetConstInfo.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'https://my.ico.edu/custom/ico/GetConstInfo.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		GETCONSTINFO_WSDL_LOCATION = url;
	}

	public GetConstInfo(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public GetConstInfo() {
		super(GETCONSTINFO_WSDL_LOCATION, new QName("http://ico.edu/",
				"GetConstInfo"));
	}

	/**
 * 	 * 
 * 	 	 * @return returns GetConstInfoSoap
 * 	 	 	 */
	@WebEndpoint(name = "GetConstInfoSoap")
	public GetConstInfoSoap getGetConstInfoSoap() {
		return super.getPort(new QName("http://ico.edu/", "GetConstInfoSoap"),
				org.sakaiproject.provider.user.GetConstInfoSoap.class);
	}

	/**
 * 	 * 
 * 	 	 * @return returns GetConstInfoSoap
 * 	 	 	 */
	@WebEndpoint(name = "GetConstInfoSoap12")
	public GetConstInfoSoap getGetConstInfoSoap12() {
		return super.getPort(
				new QName("http://ico.edu/", "GetConstInfoSoap12"),
				org.sakaiproject.provider.user.GetConstInfoSoap.class);
	}

}

