package com.isgsolutions.ibridge.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Authentication_x0020_Web_x0020_ServiceSoap", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/")
public interface AuthenticationX0020WebX0020ServiceSoap {

	/**
	 * Logins the user into the system verifying if the username and password
	 * are correct and exist in the database.
	 * 
	 * @param username
	 * @param securityPassword
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Login", action = "http://ibridge.isgsolutions.com/Authentication/Login")
	@WebResult(name = "LoginResult", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/")
	@RequestWrapper(localName = "Login", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.Login")
	@ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.LoginResponse")
	public String login(
			@WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String securityPassword,
			@WebParam(name = "username", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String username,
			@WebParam(name = "password", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String password);

	/**
	 * Logins the user into the system using the 'Unified Login' architecture.
	 * 
	 * @param username
	 * @param securityPassword
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AuthenticateUser", action = "http://ibridge.isgsolutions.com/Authentication/AuthenticateUser")
	@WebResult(name = "AuthenticateUserResult", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/")
	@RequestWrapper(localName = "AuthenticateUser", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.AuthenticateUser")
	@ResponseWrapper(localName = "AuthenticateUserResponse", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.AuthenticateUserResponse")
	public String authenticateUser(
			@WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String securityPassword,
			@WebParam(name = "username", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String username,
			@WebParam(name = "password", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String password);

	/**
	 * Verifies the existence of a user session.
	 * 
	 * @param token
	 * @param securityPassword
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AuthenticateToken", action = "http://ibridge.isgsolutions.com/Authentication/AuthenticateToken")
	@WebResult(name = "AuthenticateTokenResult", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/")
	@RequestWrapper(localName = "AuthenticateToken", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.AuthenticateToken")
	@ResponseWrapper(localName = "AuthenticateTokenResponse", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.AuthenticateTokenResponse")
	public String authenticateToken(
			@WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String securityPassword,
			@WebParam(name = "token", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String token);

	/**
	 * Deletes a user session that has been created using the AuthenticateUser
	 * method.
	 * 
	 * @param token
	 * @param securityPassword
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeleteUserSession", action = "http://ibridge.isgsolutions.com/Authentication/DeleteUserSession")
	@WebResult(name = "DeleteUserSessionResult", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/")
	@RequestWrapper(localName = "DeleteUserSession", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.DeleteUserSession")
	@ResponseWrapper(localName = "DeleteUserSessionResponse", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.DeleteUserSessionResponse")
	public String deleteUserSession(
			@WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String securityPassword,
			@WebParam(name = "token", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String token);

	/**
	 * Obtain the user that is authenticated by Imis login page.
	 * 
	 * @param cookieDomain
	 * @param securityPassword
	 * @param loginCookie
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AuthenticateCookie", action = "http://ibridge.isgsolutions.com/Authentication/AuthenticateCookie")
	@WebResult(name = "AuthenticateCookieResult", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/")
	@RequestWrapper(localName = "AuthenticateCookie", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.AuthenticateCookie")
	@ResponseWrapper(localName = "AuthenticateCookieResponse", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", className = "com.isgsolutions.ibridge.authentication.AuthenticateCookieResponse")
	public String authenticateCookie(
			@WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String securityPassword,
			@WebParam(name = "loginCookie", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String loginCookie,
			@WebParam(name = "cookieDomain", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/") String cookieDomain);

}
