package com.isgsolutions.ibridge.authentication;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * The Authentication web service is used to authenticate a user in the iMIS
 * database and implement the 'Unified Login' architecture.
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Authentication_x0020_Web_x0020_Service service = new Authentication_x0020_Web_x0020_Service();
 * AuthenticationX0020WebX0020ServiceSoap portType = service.getAuthenticationX0020WebX0020ServiceSoap();
 * portType.login(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Authentication", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", wsdlLocation = "http://isgweb.actfl.org/iservices/Authentication.asmx?wsdl")
public class AuthenticationX0020WebX0020Service extends Service {

	private final static URL AUTHENTICATIONX0020WEBX0020SERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.isgsolutions.ibridge.authentication.AuthenticationX0020WebX0020Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.isgsolutions.ibridge.authentication.AuthenticationX0020WebX0020Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://isgweb.actfl.org/iservices/Authentication.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://isgweb.actfl.org/iservices/Authentication.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		AUTHENTICATIONX0020WEBX0020SERVICE_WSDL_LOCATION = url;
	}

	public AuthenticationX0020WebX0020Service(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AuthenticationX0020WebX0020Service() {
		super(AUTHENTICATIONX0020WEBX0020SERVICE_WSDL_LOCATION, new QName(
				"http://ibridge.isgsolutions.com/Authentication/",
				"Authentication"));
	}

	/**
	 * 
	 * @return returns AuthenticationX0020WebX0020ServiceSoap
	 */
	@WebEndpoint(name = "AuthenticationSoap")
	public AuthenticationX0020WebX0020ServiceSoap getAuthenticationX0020WebX0020ServiceSoap() {
		return super.getPort(new QName(
				"http://ibridge.isgsolutions.com/Authentication/",
				"AuthenticationSoap"),
				AuthenticationX0020WebX0020ServiceSoap.class);
	}

	/**
	 * 
	 * @return returns AuthenticationX0020WebX0020ServiceSoap
	 */
	@WebEndpoint(name = "AuthenticationSoap12")
	public AuthenticationX0020WebX0020ServiceSoap getAuthenticationX0020WebX0020ServiceSoap12() {
		return super.getPort(new QName(
				"http://ibridge.isgsolutions.com/Authentication/",
				"AuthenticationSoap12"),
				AuthenticationX0020WebX0020ServiceSoap.class);
	}

	/**
	 * 
	 * @return returns AuthenticationX0020WebX0020ServiceHttpGet
	 */
	@WebEndpoint(name = "AuthenticationHttpGet")
	public AuthenticationX0020WebX0020ServiceHttpGet getAuthenticationX0020WebX0020ServiceHttpGet() {
		return super.getPort(new QName(
				"http://ibridge.isgsolutions.com/Authentication/",
				"AuthenticationHttpGet"),
				AuthenticationX0020WebX0020ServiceHttpGet.class);
	}

	/**
	 * 
	 * @return returns AuthenticationX0020WebX0020ServiceHttpPost
	 */
	@WebEndpoint(name = "AuthenticationHttpPost")
	public AuthenticationX0020WebX0020ServiceHttpPost getAuthenticationX0020WebX0020ServiceHttpPost() {
		return super.getPort(new QName(
				"http://ibridge.isgsolutions.com/Authentication/",
				"AuthenticationHttpPost"),
				AuthenticationX0020WebX0020ServiceHttpPost.class);
	}

}
