package com.isgsolutions.ibridge.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Authentication_x0020_Web_x0020_ServiceHttpGet", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AuthenticationX0020WebX0020ServiceHttpGet {

	/**
	 * Logins the user into the system verifying if the username and password
	 * are correct and exist in the database.
	 * 
	 * @param username
	 * @param securityPassword
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Login")
	@WebResult(name = "string", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", partName = "Body")
	public String login(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "securityPassword") String securityPassword,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "username") String username,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password") String password);

	/**
	 * Logins the user into the system using the 'Unified Login' architecture.
	 * 
	 * @param username
	 * @param securityPassword
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AuthenticateUser")
	@WebResult(name = "string", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", partName = "Body")
	public String authenticateUser(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "securityPassword") String securityPassword,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "username") String username,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password") String password);

	/**
	 * Verifies the existence of a user session.
	 * 
	 * @param token
	 * @param securityPassword
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AuthenticateToken")
	@WebResult(name = "string", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", partName = "Body")
	public String authenticateToken(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "securityPassword") String securityPassword,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "token") String token);

	/**
	 * Deletes a user session that has been created using the AuthenticateUser
	 * method.
	 * 
	 * @param token
	 * @param securityPassword
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeleteUserSession")
	@WebResult(name = "string", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", partName = "Body")
	public String deleteUserSession(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "securityPassword") String securityPassword,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "token") String token);

	/**
	 * Obtain the user that is authenticated by Imis login page.
	 * 
	 * @param cookieDomain
	 * @param securityPassword
	 * @param loginCookie
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AuthenticateCookie")
	@WebResult(name = "string", targetNamespace = "http://ibridge.isgsolutions.com/Authentication/", partName = "Body")
	public String authenticateCookie(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "securityPassword") String securityPassword,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "loginCookie") String loginCookie,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cookieDomain") String cookieDomain);

}
