
package com.isgsolutions.ibridge.dataaccess;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * The DataAccess web service provides pass thru capability to handle inserting, updating and selecting data for tables stored in iMIS.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataAccess", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", wsdlLocation = "http://isgweb.actfl.org/iservices/DataAccess.asmx?wsdl")
public class DataAccessX0020WebX0020Service
    extends Service
{

    private final static URL DATAACCESSX0020WEBX0020SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.isgsolutions.ibridge.dataaccess.DataAccessX0020WebX0020Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.isgsolutions.ibridge.dataaccess.DataAccessX0020WebX0020Service.class.getResource(".");
            url = new URL(baseUrl, "http://isgweb.actfl.org/iservices/DataAccess.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://isgweb.actfl.org/iservices/DataAccess.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATAACCESSX0020WEBX0020SERVICE_WSDL_LOCATION = url;
    }

    public DataAccessX0020WebX0020Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataAccessX0020WebX0020Service() {
        super(DATAACCESSX0020WEBX0020SERVICE_WSDL_LOCATION, new QName("http://ibridge.isgsolutions.com/DataAccess/", "DataAccess"));
    }

    /**
     * 
     * @return
     *     returns DataAccessX0020WebX0020ServiceSoap
     */
    @WebEndpoint(name = "DataAccessSoap")
    public DataAccessX0020WebX0020ServiceSoap getDataAccessX0020WebX0020ServiceSoap() {
        return super.getPort(new QName("http://ibridge.isgsolutions.com/DataAccess/", "DataAccessSoap"), DataAccessX0020WebX0020ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataAccessX0020WebX0020ServiceSoap
     */
    @WebEndpoint(name = "DataAccessSoap")
    public DataAccessX0020WebX0020ServiceSoap getDataAccessX0020WebX0020ServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibridge.isgsolutions.com/DataAccess/", "DataAccessSoap"), DataAccessX0020WebX0020ServiceSoap.class, features);
    }

}
