
package com.isgsolutions.ibridge.dataaccess;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DataAccess_x0020_Web_x0020_ServiceSoap", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
@XmlSeeAlso({
    org.w3._2001.xmlschema.ObjectFactory.class,
    com.isgsolutions.ibridge.dataaccess.ObjectFactory.class
})
public interface DataAccessX0020WebX0020ServiceSoap {


    /**
     * Executes an update/insert statement in the database.
     * 
     * @param sqlStatement
     * @param securityPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecuteSQLStatement", action = "http://ibridge.isgsolutions.com/DataAccess/ExecuteSQLStatement")
    @WebResult(name = "ExecuteSQLStatementResult", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
    @RequestWrapper(localName = "ExecuteSQLStatement", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteSQLStatement")
    @ResponseWrapper(localName = "ExecuteSQLStatementResponse", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteSQLStatementResponse")
    public String executeSQLStatement(
        @WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String securityPassword,
        @WebParam(name = "sqlStatement", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String sqlStatement);

    /**
     * Executes a select statement in the database.
     * 
     * @param sqlStatement
     * @param securityPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecuteSelectSQLStatement", action = "http://ibridge.isgsolutions.com/DataAccess/ExecuteSelectSQLStatement")
    @WebResult(name = "ExecuteSelectSQLStatementResult", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
    @RequestWrapper(localName = "ExecuteSelectSQLStatement", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteSelectSQLStatement")
    @ResponseWrapper(localName = "ExecuteSelectSQLStatementResponse", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteSelectSQLStatementResponse")
    public String executeSelectSQLStatement(
        @WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String securityPassword,
        @WebParam(name = "sqlStatement", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String sqlStatement);

    /**
     * Executes a stored procedure in the iMIS database.
     * 
     * @param name
     * @param parameters
     * @param securityPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecuteStoredProcedure", action = "http://ibridge.isgsolutions.com/DataAccess/ExecuteStoredProcedure")
    @WebResult(name = "ExecuteStoredProcedureResult", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
    @RequestWrapper(localName = "ExecuteStoredProcedure", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteStoredProcedure")
    @ResponseWrapper(localName = "ExecuteStoredProcedureResponse", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteStoredProcedureResponse")
    public String executeStoredProcedure(
        @WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String securityPassword,
        @WebParam(name = "name", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String name,
        @WebParam(name = "parameters", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String parameters);

    /**
     * Executes a stored procedure in the iMIS database, expecting a return value.
     * 
     * @param name
     * @param parameters
     * @param securityPassword
     * @return
     *     returns com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedureResponse.ExecuteDatasetStoredProcedureResult
     */
    @WebMethod(operationName = "ExecuteDatasetStoredProcedure", action = "http://ibridge.isgsolutions.com/DataAccess/ExecuteDatasetStoredProcedure")
    @WebResult(name = "ExecuteDatasetStoredProcedureResult", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
    @RequestWrapper(localName = "ExecuteDatasetStoredProcedure", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedure")
    @ResponseWrapper(localName = "ExecuteDatasetStoredProcedureResponse", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedureResponse")
    public com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedureResponse.ExecuteDatasetStoredProcedureResult executeDatasetStoredProcedure(
        @WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String securityPassword,
        @WebParam(name = "name", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String name,
        @WebParam(name = "parameters", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String parameters);

    /**
     * Executes a stored procedure in the iMIS database, expecting a return value.
     * 
     * @param name
     * @param parameters
     * @param securityPassword
     * @return
     *     returns com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedureNoLogResponse.ExecuteDatasetStoredProcedureNoLogResult
     */
    @WebMethod(operationName = "ExecuteDatasetStoredProcedureNoLog", action = "http://ibridge.isgsolutions.com/DataAccess/ExecuteDatasetStoredProcedureNoLog")
    @WebResult(name = "ExecuteDatasetStoredProcedureNoLogResult", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
    @RequestWrapper(localName = "ExecuteDatasetStoredProcedureNoLog", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedureNoLog")
    @ResponseWrapper(localName = "ExecuteDatasetStoredProcedureNoLogResponse", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedureNoLogResponse")
    public com.isgsolutions.ibridge.dataaccess.ExecuteDatasetStoredProcedureNoLogResponse.ExecuteDatasetStoredProcedureNoLogResult executeDatasetStoredProcedureNoLog(
        @WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String securityPassword,
        @WebParam(name = "name", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String name,
        @WebParam(name = "parameters", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String parameters);

    /**
     * Executes a stored procedure in the iMIS database, without expecting a return value.
     * 
     * @param name
     * @param parameters
     * @param securityPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecuteNonQueryStoredProcedure", action = "http://ibridge.isgsolutions.com/DataAccess/ExecuteNonQueryStoredProcedure")
    @WebResult(name = "ExecuteNonQueryStoredProcedureResult", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
    @RequestWrapper(localName = "ExecuteNonQueryStoredProcedure", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteNonQueryStoredProcedure")
    @ResponseWrapper(localName = "ExecuteNonQueryStoredProcedureResponse", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/", className = "com.isgsolutions.ibridge.dataaccess.ExecuteNonQueryStoredProcedureResponse")
    public String executeNonQueryStoredProcedure(
        @WebParam(name = "securityPassword", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String securityPassword,
        @WebParam(name = "name", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String name,
        @WebParam(name = "parameters", targetNamespace = "http://ibridge.isgsolutions.com/DataAccess/")
        String parameters);

}
